version: "3.0"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: "loggy-dynamodb"
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb_data:/data
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: "loggy-dynamodb-admin"
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
  fastapi:
    container_name: "loggy-fastapi"
    build: 
      context: ./packages/backend
      dockerfile: ./Dockerfile
      target: ${STAGE:-local}
    ports:
      - 5000:8080
    volumes:
      - ./packages/backend/backend:/app
    env_file:
      - packages/backend/.env
  awscli:
    build: ./.docker/aws_cli
    entrypoint: []
    tty: true
    command:
      /bin/bash -c "bash bin/*.sh"
    depends_on:
      - dynamodb
  postgres:
    image: postgres:14
    container_name: loggy-postgres
    tty: true
    ports:
      - 5432:5432
    volumes:
      - rdb_data:/var/lib/postgresql/data
    env_file:
      - packages/backend/.env

volumes:
  rdb_data:
  dynamodb_data:
