"""create users, user_details, lodgings, stays

Revision ID: 874c17f78d9d
Revises: 
Create Date: 2022-11-06 04:29:09.049105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '874c17f78d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), ),
    sa.Column('name', sa.String(), ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('lodgings',
    sa.Column('id', postgresql.UUID(as_uuid=True), ),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lodgings_id'), 'lodgings', ['id'], unique=False)
    op.create_table('stays',
    sa.Column('id', postgresql.UUID(as_uuid=True), ),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stays_id'), 'stays', ['id'], unique=False)
    op.create_table('user_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), ),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), ),
    sa.Column('email', sa.String(), ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_details_id'), 'user_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_stays_id'), table_name='stays')
    op.drop_table('stays')
    op.drop_index(op.f('ix_lodgings_id'), table_name='lodgings')
    op.drop_table('lodgings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
