[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Motoya Kondo <motoya.kon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.85.0"
typer = "^0.6.1"
boto3 = "^1.24.80"
postgres = "^4.0"
SQLAlchemy = "^1.4.41"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
